[build]
  bin = "./tmp/tailmplx"
  cmd = "templ generate && go build -o ./tmp/ && tailwindcss -c web/tailwind.config.js -i web/input.css -o web/public/assets/output.css"
  delay = 1000
  exclude_dir = ["web", "tmp", ".git"]
  exclude_regex = [".*_templ.go"]
  include_ext = ["go", "templ"]
