[build]
  bin = "./tmp/main"
  cmd = "templ generate && tailwindcss -c web/tailwind.config.js -i web/input.css -o web/public/assets/output.css && go build -o ./tmp/main"
  delay = 1000
  exclude_dir = ["web/public", "tmp", ".git"]
  exclude_regex = [".*_templ.go"]
  include_ext = ["go", "templ", "css"]
