
[build]
  bin = "./tmp/main"
  cmd = "just build"
  delay = 1000
  exclude_dir = ["public", "tmp", "styles", ".git"]
  exclude_regex = [".*_templ.go"]
  include_ext = ["go", "templ", "css"]

[misc]
  clean_on_exit = false
