name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - uses: actions/checkout@v4

      - name: Installing Dependencies
        run: |
          npm i -g tailwindcss
          go mod tidy

      # Running Tailwind first to create all subfolders
      - name: Bundling CSS
        run: tailwindcss --minify -c web/tailwind.config.js -i web/input.css -o build/web/public/assets/output.css

      - name: Building Binary
        run: go build -o ./build/

      - name: Copying Necessary Files
        run: |
          cp -r web/public build/web/public

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./build
