name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v4

      - name: Installing Dependencies
        run: |
          npm i -g tailwindcss
          go mod download

      - name: Running Release Script
        run: ./scripts/release.sh

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: ./release/
